## Please use make index to update this file
native_methods = """
AddNodeNetwork
AddNodeNetworkSetting
AddNodeNetworkSettingType
AddSliceAttribute
AddSliceAttributeType
DeleteNodeNetwork
DeleteNodeNetworkSetting
DeleteNodeNetworkSettingType
DeleteSliceAttribute
DeleteSliceAttributeType
GetNodeNetworkSettingTypes
GetNodeNetworkSettings
GetNodeNetworks
GetSliceAttributeTypes
GetSliceAttributes
UpdateNodeNetwork
UpdateNodeNetworkSetting
UpdateNodeNetworkSettingType
UpdateSliceAttribute
UpdateSliceAttributeType
""".split()
