#!/usr/bin/python /usr/bin/plcsh
# -*- python -*-

#
# run this before the 'db' step
# various object creation functions might depend
# on the tagtype being created, like
# 'vref' and 'initscript' for slices, and possibly more
#
# priority: 899
#

from PLC.Accessor import AccessorSingleton

if __name__ == '__main__':
    print "service plc start accessors : ensuring creation and consistency of accessor tags"
    AccessorSingleton(api).run_all_tag_locators()

